<a href="https://colab.research.google.com/github/iyappan24/Applied-AI-Notebooks/blob/master/Machine_Learning_Data_Pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AMAZON FINE FOOD REVIEWS : POLARITY CLASSIFICATION USIGN K-NN

Data Source: https://www.kaggle.com/snap/amazon-fine-food-reviews

The Amazon Fine Food Reviews dataset consists of reviews of fine foods from Amazon.<br>

Number of reviews: 568,454<br>
Number of users: 256,059<br>
Number of products: 74,258<br>
Timespan: Oct 1999 - Oct 2012<br>
Number of Attributes/Columns in data: 10 

Attribute Information:

1. Id
2. ProductId - unique identifier for the product
3. UserId - unqiue identifier for the user
4. ProfileName
5. HelpfulnessNumerator - number of users who found the review helpful
6. HelpfulnessDenominator - number of users who indicated whether they found the review helpful or not
7. Score - rating between 1 and 5
8. Time - timestamp for the review
9. Summary - brief summary of the review
10. Text - text of the review

### Installing Libraries and Dependencies in Google Drive

In [1]:
!pip install gensim

    100% |████████████████████████████████| 23.6MB 702kB/s 
    100% |████████████████████████████████| 1.4MB 13.5MB/s 
    100% |████████████████████████████████| 133kB 27.3MB/s 
    100% |████████████████████████████████| 61kB 21.0MB/s 
    100% |████████████████████████████████| 4.7MB 5.7MB/s 
    100% |████████████████████████████████| 552kB 13.7MB/s 
  Running setup.py bdist_wheel for smart-open ... - \ done
  Stored in directory: /root/.cache/pip/wheels/23/00/44/e5b939f7a80c04e32297dbd6d96fa3065af89ecf57e2b5f89f
  Running setup.py bdist_wheel for bz2file ... - done
  Stored in directory: /root/.cache/pip/wheels/81/75/d6/e1317bf09bf1af5a30befc2a007869fa6e1f516b8f7c591cb9
Successfully built smart-open bz2file


In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns 
import nltk
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer

from gensim.models import Word2Vec
from gensim.models import KeyedVectors
import pickle
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

from tqdm import tqdm
import sqlite3
import re
from datetime import datetime
import pickle
from google.colab import files

--------------
##Mounting google drive to get the data from the google drive folder

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


## Loading the data

The dataset is available in two forms
1. .csv file
2. SQLite Database

In order to load the data, We have used the SQLITE dataset as it easier to query the data and visualise the data efficiently.
<br> 

Here as we only want to get the global sentiment of the recommendations (positive or negative), we will purposefully ignore all Scores equal to 3. If the score id above 3, then the recommendation wil be set to "positive". Otherwise, it will be set to "negative".

In [0]:
con = sqlite3.connect('/content/gdrive/My Drive/AppliedAI/Amazon Fine Food Reviews/database.sqlite')

In [0]:
filtered_data = pd.read_sql_query(""" SELECT * FROM Reviews WHERE Score != 3 """, con)

In [9]:
filtered_data.head(3)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...

In [0]:
def partition(x):
    if x < 3:
        return 0
    return 1

In [0]:
actualScore = filtered_data['Score']
positiveNegative = actualScore.map(partition) 
filtered_data['Score'] = positiveNegative

In [12]:
filtered_data.head(3)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      1  1303862400   
1                     0                       0      0  1346976000   
2                     1                       1      1  1219017600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...

In [13]:
print("Number of data points in our data", filtered_data.shape)

Number of data points in our data (525814, 10)


** Removing the Duplicate entries ** 

In [0]:
sorted_data=filtered_data.sort_values('ProductId', axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')

In [15]:
final=sorted_data.drop_duplicates(subset={"UserId","ProfileName","Time","Text"}, keep='first', inplace=False)
final.shape

(364173, 10)

## TEXT PRE-PROCESSING

Now that we have finished deduplication our data requires some preprocessing before we go on further with analysis and making the prediction model.

Hence in the Preprocessing phase we do the following in the order below:-

1. Begin by removing the html tags
2. Remove any punctuations or limited set of special characters like , or . or # etc.
3. Check if the word is made up of english letters and is not alpha-numeric
4. Check to see if the length of the word is greater than 2 (as it was researched that there is no adjective in 2-letters)
5. Convert the word to lowercase
6. Remove Stopwords
7. Finally Snowball Stemming the word (it was obsereved to be better than Porter Stemming)<br>

After which we collect the words used to describe positive and negative reviews

** REMOVING HTML TAGS  and PUNCTUATIONS** 

In [0]:
def cleanhtml(sentence): #function to clean the word of any html-tags
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, ' ', sentence)
    return cleantext

def cleanpunc(sentence): #function to clean the word of any punctuation or special characters
    cleaned = re.sub(r'[?|!|\'|"|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    return  cleaned

In [0]:
stop = set(stopwords.words('english'))
sno = nltk.stem.SnowballStemmer('english')

In [0]:
#removing not and no from list of stopwords 
stop.remove('not')
stop.remove('no')

In [21]:
if not os.path.isfile('final.sqlite'):
    i=0
    str1=' '
    final_string=[]
    all_positive_words=[] # store words from +ve reviews here
    all_negative_words=[] # store words from -ve reviews here.
    s=''
    for sent in tqdm(final['Text'].values):
        filtered_sentence=[]
        #print(sent);
        sent=cleanhtml(sent) # remove HTMl tags
        for w in sent.split():
            for cleaned_words in cleanpunc(w).split():
                if((cleaned_words.isalpha()) & (len(cleaned_words)>2)):    
                    if(cleaned_words.lower() not in stop):
                        s=(sno.stem(cleaned_words.lower())).encode('utf8')
                        filtered_sentence.append(s)
                        if (final['Score'].values)[i] == 'positive': 
                            all_positive_words.append(s) #list of all words used to describe positive reviews
                        if(final['Score'].values)[i] == 'negative':
                            all_negative_words.append(s) #list of all words used to describe negative reviews reviews
                    else:
                        continue
                else:
                    continue 
        #print(filtered_sentence)
        str1 = b" ".join(filtered_sentence) #final string of cleaned words
        #print("***********************************************************************")

        final_string.append(str1)
        i+=1
        
#############---- storing the data into .sqlite file ------########################
    final['CleanedText']=final_string #adding a column of CleanedText which displays the data after pre-processing of the review 
    final['CleanedText']=final['CleanedText'].str.decode("utf-8")
        # store final table into an SQlLite table for future.
    conn = sqlite3.connect('final.sqlite')
    c=conn.cursor()
    conn.text_factory = str
    final.to_sql('Reviews', conn,  schema=None, if_exists='replace', \
                 index=True, index_label=None, chunksize=None, dtype=None)
    conn.close()

100%|██████████| 364173/364173 [09:09<00:00, 662.48it/s]


In [0]:
if os.path.isfile('final.sqlite'):
    conn = sqlite3.connect('final.sqlite')
    final = pd.read_sql_query(""" SELECT * FROM Reviews WHERE Score != 3 """, conn)
    conn.close()

In [23]:
final.head(2)

index      Id   ProductId          UserId      ProfileName  \
0  138706  150524  0006641040   ACITT7DI6IDDL  shari zychinski   
1  138688  150506  0006641040  A2IW4PEEKO2R0U            Tracy   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     0                       0      1   939340800   
1                     1                       1      1  1194739200   

                                      Summary  \
0                   EVERY book is educational   
1  Love the book, miss the hard cover version   

                                                Text  \
0  this witty little book makes my son laugh at l...   
1  I grew up reading these Sendak books, and watc...   

                                         CleanedText  
0  witti littl book make son laugh loud recit car...  
1  grew read sendak book watch realli rosi movi i...

In [0]:
final = final.sort_values(by ='Time',ascending= True).copy(deep=True)

In [33]:
final.head(15)

index      Id   ProductId          UserId               ProfileName  \
0    138706  150524  0006641040   ACITT7DI6IDDL           shari zychinski   
30   138683  150501  0006641040   AJ46FKXOVC7NR        Nicholas A Mesiano   
424  417839  451856  B00004CXX9   AIUWLEQ1ADEG5          Elizabeth Medina   
330  346055  374359  B00004CI84  A344SMIA5JECGM           Vincent P. Ross   
423  417838  451855  B00004CXX9   AJH6LUC1UT1ON  The Phantom of the Opera   
245  346116  374422  B00004CI84  A1048CYU0OV4O8              Judy L. Eans   
308  346041  374343  B00004CI84   A1B2IZU1JLZA6                       Wes   
215   70688   76882  B00002N8SM  A32DW342WBJ6BX               Buttersugar   
261  346141  374450  B00004CI84   ACJR7EQF9S6FP          Jeremy Robertson   
325  346094  374400  B00004CI84  A2DEE7F9XKP3ZR                    jerome   
427  417883  451903  B00004CXX9  A2DEE7F9XKP3ZR                    jerome   
241    1146    1245  B00002Z754  A29Z5PI9BW2PU3                    Robbie   
242    1145    1244  B00002Z754  A3B8RCEI0FXFI6                 B G Chase   
485  121041  131217  B00004RAMX   A5NQLNC6QPGSI                 Kim Nason   
868  138017  149789  B00004S1C6  A1KXONFPU2XQ5K          Stephanie Manley   

     HelpfulnessNumerator  HelpfulnessDenominator  Score       Time  \
0                       0                       0      1  939340800   
30                      2                       2      1  940809600   
424                     0                       0      1  944092800   
330                     1                       2      1  944438400   
423                     0                       0      1  946857600   
245                     2                       2      1  947376000   
308                    19                      23      0  948240000   
215                     0                       0      1  948672000   
261                     2                       3      1  951523200   
325                     0                       3      1  959990400   
427                     0                       1      1  959990400   
241                     7                       7      1  961718400   
242                    10                      10      1  962236800   
485                     7                       8      1  965001600   
868                    26                      28      1  965779200   

                                               Summary  \
0                            EVERY book is educational   
30   This whole series is great way to spend time w...   
424                               Entertainingl Funny!   
330                            A modern day fairy tale   
423                                         FANTASTIC!   
245                                              GREAT   
308    WARNING: CLAMSHELL EDITION IS EDITED TV VERSION   
215                             A sure death for flies   
261           Bettlejuice...Bettlejuice...BETTLEJUICE!   
325      Research - Beatlejuice video - French version   
427                                           Research   
241                                      Great Product   
242                     WOW Make your own 'slickers' !   
485                           End your Gopher Problems   
868                                       A must have!   

                                                  Text  \
0    this witty little book makes my son laugh at l...   
30   I can remember seeing the show when it aired o...   
424  Beetlejuice is a well written movie ..... ever...   
330  A twist of rumplestiskin captured on film, sta...   
423  Beetlejuice is an excellent and funny movie. K...   
245  THIS IS ONE MOVIE THAT SHOULD BE IN YOUR MOVIE...   
308  I, myself always enjoyed this movie, it's very...   
215  I bought a few of these after my apartment was...   
261  What happens when you say his name three times...   
325  I'm getting crazy.I'm looking for Beatlejuice ...   
427  I'm getting crazy.<p>Is it really impossible t...   
241  This w

** Function to return the time stamp in DD/MM/YY HH : MM : SS format from UNIX FORMAT **

In [0]:
def ret_time(col):
  return datetime.utcfromtimestamp(col).strftime('%Y-%m-%d %H:%M:%S')

In [0]:
final['Formated_time'] = final['Time'].apply(ret_time)

In [46]:
print(min(final['Formated_time']))
print(max(final['Formated_time']))

1999-10-08 00:00:00
2012-10-26 00:00:00


** Function to return the year of the timestamp **

In [0]:
def ret_year(col):
  val = pd.to_datetime(col)
  return val.year

In [0]:
final['Year'] = final['Formated_time'].apply(ret_year)

** APPROACH:** <br>
1. Split the data into 70 - 30 where Train will have 70k points and test will have 30k points for ** WORD2VEC and TFIDF WORD2VEC representation**
2. For ** BOW and TFIDF** representation we are splitting the dataset into 60k for train, 20k for CV, 20k for Test for reducing the time in predicting sparse matrices.
3. For each Featurisation perform Cross validation for different K and find the optimal K and report the test accuracy
4.. Standarad Scale the data before training and download the interim files which are generated for future re-use

In [0]:
#getting the already pre-processed final.sqlite stored in gdrive for emergency purposes when google cloab crashes
conn = sqlite3.connect('/content/gdrive/My Drive/AppliedAI/Amazon Fine Food Reviews/final.sqlite')
final = pd.read_sql_query(""" SELECT * FROM Reviews WHERE Score != 3 """, conn)
conn.close()

In [0]:
#sorting the data according to the time in ascending order
final = final.sort_values(by='Formated_time').copy(deep=True)


# 70 - 30 split 

Taking 70k Datapoints for Training and 30k Datapoints for testing 

In [0]:
train = final[0:70000]

In [0]:
test = final[70001:100001]

In [10]:
pd.unique(train['Year'])

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

In [11]:
pd.unique(test['Year'])

array([2009, 2010])

------------------

The data span of train is almost 10 years  and test is 1.5 years. 

-----------

## FEATURIZATION 1 : AVERAGE WORD2VEC 

In [0]:
#training the word2vec on the train data 
i =0 
list_of_sent = []
for sent in train['CleanedText'].values:
    list_of_sent.append(sent.split())

w2v_model=Word2Vec(list_of_sent,min_count=5,size=50, workers=4)

In [0]:
i =0 
list_of_sent_train = []
for sent in train['CleanedText'].values:
    list_of_sent_train.append(sent.split())

In [0]:
i =0 
list_of_sent_test = []
for sent in test['CleanedText'].values:
    list_of_sent_test.append(sent.split())

Preparing the Train dataset : Avg Word2Vec per each sentence in the training dataset Output : X_train , Y_train( Polarity) : Corresponding

In [24]:
sent_vectors_train = []
for sent in tqdm(list_of_sent_train): # for each review/sentence
    sent_vec = np.zeros(50) # as word vectors are of zero length
    cnt_words =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        if word in w2v_model:
            vec = w2v_model.wv[word]
            sent_vec += vec
            cnt_words += 1
    if cnt_words != 0:
        sent_vec /= cnt_words
    sent_vectors_train.append(sent_vec)

c= []
for i in range(0,50):
    c.append("Vector " + str(i+1))
    
X_train = pd.DataFrame(sent_vectors_train,columns=c)
y_train = train['Score']

100%|██████████| 70000/70000 [01:17<00:00, 907.21it/s]


Preparing the Test dataset : Avg Word2Vec per each sentence in the test dataset Output : X_test , Y_test( Polarity) : Corresponding

In [35]:
sent_vectors_test= []
for sent in tqdm(list_of_sent_test): # for each review/sentence
    sent_vec = np.zeros(50) # as word vectors are of zero length
    cnt_words =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        if word in w2v_model:
            vec = w2v_model.wv[word]
            sent_vec += vec
            cnt_words += 1
    if cnt_words != 0:
        sent_vec /= cnt_words
    sent_vectors_test.append(sent_vec)

c= []
for i in range(0,50):
    c.append("Vector " + str(i+1))
    
X_test = pd.DataFrame(sent_vectors_test,columns=c)
y_test = list(test['Score'])

100%|██████████| 30000/30000 [00:27<00:00, 1071.72it/s]


## FEATURIZATION 2 : TFIDF WORD2VEC

In [0]:
#traing the tfidfVectorizer only for train dataset
model = TfidfVectorizer(lowercase=True,ngram_range=(1,1))
tf_idf_matrix = model.fit_transform(train['CleanedText'].values)
# we are converting a dictionary with word as a key, and the idf as a value
dictionary = dict(zip(model.get_feature_names(), list(model.idf_)))

_________________

Preparing the TFIDF WORD2VEC  of Train data 
_________________


In [74]:
tfidf_sent_vectors = []; # the tfidf-w2v for each sentence/review is stored in this list
row=0;
for sent in tqdm(list_of_sent_train): # for each review/sentence 
    sent_vec = np.zeros(50) # as word vectors are of zero length
    weight_sum =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        if word in w2v_model:
            vec = w2v_model.wv[word]
#             tf_idf = tf_idf_matrix[row, tfidf_feat.index(word)]
            # to reduce the computation we are 
            # dictionary[word] = idf value of word in whole courpus
            # sent.count(word) = tf values of word in this review
            tf_idf = dictionary[word]*sent.count(word)
            sent_vec += (vec * tf_idf)
            weight_sum += tf_idf
    if weight_sum != 0:
        sent_vec /= weight_sum
    tfidf_sent_vectors.append(sent_vec)
    row += 1
  
#------------------------------------------------------------------------------
c= []
for i in range(0,50):
    c.append("Vector " + str(i+1))
train_tfw2v = pd.DataFrame(tfidf_sent_vectors,columns=c)
train_tfw2v['Score']= list(train['Score'])

100%|██████████| 70000/70000 [00:45<00:00, 1533.88it/s]


_________________

Preparing the TFIDF WORD2VEC  of Test data 
_________________


In [79]:
tfidf_sent_vectors = []; # the tfidf-w2v for each sentence/review is stored in this list
row=0;
for sent in tqdm(list_of_sent_test): # for each review/sentence 
    sent_vec = np.zeros(50) # as word vectors are of zero length
    weight_sum =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        if word in w2v_model:
            vec = w2v_model.wv[word]
#             tf_idf = tf_idf_matrix[row, tfidf_feat.index(word)]
            # to reduce the computation we are 
            # dictionary[word] = idf value of word in whole courpus
            # sent.count(word) = tf values of word in this review
            tf_idf = dictionary[word]*sent.count(word)
            sent_vec += (vec * tf_idf)
            weight_sum += tf_idf
    if weight_sum != 0:
        sent_vec /= weight_sum
    tfidf_sent_vectors.append(sent_vec)
    row += 1
  
#------------------------------------------------------------------------------
c= []
for i in range(0,50):
    c.append("Vector " + str(i+1))
test_tfw2v = pd.DataFrame(tfidf_sent_vectors,columns=c)
test_tfw2v['Score']= list(test['Score'])

100%|██████████| 30000/30000 [00:21<00:00, 1414.42it/s]


-------------

# 60-20-20 SPLIT


In [0]:
train = final[0:60000]
cv = final[60001:80001]
test = final[80001:100001]

In [0]:
y_train = train['Score']
y_cv = cv['Score']
y_test = test['Score']

In [51]:
pd.unique(train['Year'])

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

In [52]:
pd.unique(cv['Year'])

array([2009, 2010])

In [53]:
pd.unique(test['Year'])

array([2010])

## FEATURIZATION 3 : BOW

In [0]:
#intiailising the bag words count vectorizer
count_vect = CountVectorizer() #in scikit-learn
train_bow = count_vect.fit_transform(train['CleanedText'].values)
test_bow = count_vect.transform(test['CleanedText'].values)
cv_bow = count_vect.transform(cv['CleanedText'].values)

## FEATURIZATION 4 : TFIDF : UNIGRAM TF_IDF




In [0]:
tf_idf = TfidfVectorizer(lowercase=True,ngram_range=(1,1))
train_tfidf = tf_idf.fit_transform(train['CleanedText'].values)
test_tfidf = tf_idf.transform(test['CleanedText'].values)
cv_tfidf = tf_idf.transform(cv['CleanedText'].values)

In [0]:
pickle.dump(y_cv,open('y_cv.sav','wb'))

In [0]:
files.download('y_test.sav') 

In [80]:
!ls -l

total 111860
-rw-r--r-- 1 root root 12241858 Nov  1 07:34 avg_word2vec_test.sav
-rw-r--r-- 1 root root 28561864 Nov  1 07:22 avg_word2vec_train.sav
-rw-r--r-- 1 root root  7608347 Nov  1 12:33 cv_bow.sav
-rw-r--r-- 1 root root  7608320 Nov  1 12:36 cv_tfidf.sav
drwx------ 3 root root     4096 Nov  1 06:13 gdrive
drwxr-xr-x 2 root root     4096 Oct 30 22:07 sample_data
-rw-r--r-- 1 root root  7439027 Nov  1 12:33 test_bow.sav
-rw-r--r-- 1 root root  7439000 Nov  1 12:36 test_tfidf.sav
-rw-r--r-- 1 root root 21808296 Nov  1 12:33 train_bow.sav
-rw-r--r-- 1 root root 21808296 Nov  1 12:44 train_tfidf.sav


----------------
<br>

### ALL THE DATA OF TRAIN AND TEST OF RESPECTIVE FEATURIZATIONS HAS BEEN PUSHED INTO GOOGLE DRIVE IN PICKLE SERIALIZED FORMAT FOR DIRECT FUTURE USE